### PR TITLE
AddedExplanationofSwitchStatment

### PR DESCRIPTION
**Pull request by AayushSaini101**
Added Explanation of the switch program.

### CODE REVIEW

**Review by Utkarsh1504 — COMMENTED** [review]
hey, @AayushSaini101 please remove the content from the body of the code(```java) and also make the explanation in bullet-points. you can take help from [`If-else statements`](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/io-conditionals.md#if-else-statements) and do markdown according to that.

Also, one last thing read our [contribution](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson) guidelines for the naming guidelines.

Thank you for your PR, Content Looks great.

**Comment by AayushSaini101** [comment]
Ok @Utkarsh1504  I will change it accordingly

**Comment by satyamgupta1495** [comment]
is this issue still open?

**Comment by Utkarsh1504** [comment]
@satyamgupta1495 This is a Pull request, not an issue.

**Comment by Utkarsh1504** [comment]
this issue has been resolved

**Pull request closed without merging**
