### PR TITLE
added the lecture notes and some example

### PR DESCRIPTION
**Pull request by aryanbramhane**

### CODE REVIEW

**Comment by Utkarsh1504** [comment]
@aryanbramhane a lot of information is missing, please make another commit.
Please refer to here, https://www.youtube.com/watch?v=vvanI8NRlSI, and add Kunal's notes as they are best with consisting great information.
Thank you!

**Comment by aryanbramhane** [comment]
Ahh, ok I added most of the stuff from his lecture only. But can you tell me what exactly is missing

**Review by Utkarsh1504 — CHANGES_REQUESTED** [review]
Please change the entire content

**Comment by aryanbramhane** [comment]
ok

**Comment by Utkarsh1504** [comment]
@aryanbramhane you have just written one line definition It needs an explanation for any beginner who will come to learn from this site will not able to digest it.
- program explanations
- memory concept in case of methods
- Overloading
- shadowing 
please explain these concepts in a little bit more detail

**Comment by Utkarsh1504** [comment]
Hey @aryanbramhane you if need any kind of help please feel free to ask, you can use
https://github.com/Vrukshali-26/DSA/blob/main/6-Functions%20and%20methods.pdf
notes and explain according to that, this will help you a lot.
Just do the changes, I'll be really happy to merge your PR. Thanks

**Comment by aryanbramhane** [comment]
I am following the same course and most of the notes that I had made are from that course only. Surly adding some content in this

**Comment by Utkarsh1504** [comment]
@aryanbramhane please resolve the merge conflict as the lesson was updated by a guy, but don't you worry, the issue is all yours, please do improvements in his content, I'll merge your PR too. Thank you!

**Pull request closed without merging**
