### PR TITLE
improvement:operators.md

### LINKED ISSUE #8: improve: the explanations of the logical operators AND and OR: && vs. & and || vs. |
### ⭐ Summary

Descriptions of &&(AND) and || (OR) might be misleading and less accurate:

```markdown
- `&&`: AND used to perform logical AND operation. It gives true if both the operands have true value.
- `||`: OR used to perform logical OR operation. It gives true if either of the operands have true value.
```

For instance, || gives true if the 1st operand has a  true value, and it will not try to evaluate the 2nd operand.
It might be helpful to mention **&** and **|** first, and then present a comparison between **&** and **&&**, as well as **|** and **||**.

### 💻 Location

See following markdown files:

https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md?plain=1#L73

https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md?plain=1#L74

### ❌ Additional Info

_No response_

### PR DESCRIPTION
**Pull request by roshaan005**
Fixes #8

#### Short description of what this resolves:
The issue related to the unclear explanation of logical operators in java will be resolved with this pull request.

improve: the explanations of the logical operators AND and OR: && vs. & and || vs. | 

#### What Changes proposed in this pull request:

- improves the explanation of logical operators 
- explicitly mentions the differences between a bitwise and logical operator

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] Added documentation so that the program is self-explanatory and educational.
- [x] PR title follows semantic [commit guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
improves the operators.md lesson.

### CODE REVIEW

**Review by Utkarsh1504 — CHANGES_REQUESTED** [review]
please remove .vscode/setting.json file,
Thank you for Improving this lesson.

**Comment by roshaan005** [comment]
sorry for that , I removed it , could you please check now?

**Review by Utkarsh1504 — APPROVED** [review]

**Comment by Utkarsh1504** [comment]
Thank you for your contribution. I appreciate your hard work. Keep Contributing 👍🏼

**Comment by roshaan005** [comment]
Was a pleasure working on this one. Thank you for being patient!

**Pull request merged**
