### PR TITLE
Added information to space-complexity.md

### PR DESCRIPTION
**Pull request by ParnaviKulkarni**
I added content for space-complexity.md. It is primarily based on Sahani & Horowitz DSA book and other online resources. I've also included multiple examples. This is my first actual contribution so please excuse my in-experience and d tell if any modifications are needed.
Also corrected a small grammatical error I noticed in intro-complexity.md
Thank you!

### CODE REVIEW

**Comment by ParnaviKulkarni** [comment]
@Utkarsh1504 I wasn't aware that we can work only on statements mentioned in the issue section. Still, I request you to go through my document, It consists of a lot of information and I think it might be suitable for your website. Thank you!
Sorry for the inconvenience!

**Comment by Utkarsh1504** [comment]
@ParnaviKulkarni No, we provide the minimum required syllabus that needs to be present in the lesson but you can add more information if you want, it depends on the contributor how much hard work they want to do. I'll review your Pull Request.

**Comment by ParnaviKulkarni** [comment]
Okay Thank you so much!

**Comment by Utkarsh1504** [comment]
@ParnaviKulkarni I haven't opened an issue on **space complexity**, I am opening an issue right now and will assign you as well then link this PR with that issue then I will review.
till then, please undo your contribution in `intro-complexity.md` file because it is already assigned to someone else. Keep the space complexity contribution as it is just change the other on.
Thanks

**Comment by Utkarsh1504** [comment]
And please follow our contribution guideline and read the README of the repo, you should make a branch and then start your contribution, before making a pull request you should open an issue and then make a PR, so these kinds of things. so please read that

**Comment by ParnaviKulkarni** [comment]
I am sorry will you please guide me through how to undo my contribution to intro-complexity.md? Should I make a new PR?
Yes I will keep the instructions in mind from now on.

**Comment by ParnaviKulkarni** [comment]
I will remake the pull request.

**Comment by Utkarsh1504** [comment]
Screenshot (147)
**Ok so here you have changed that `i` to `I`**, In order to undo this go in that file, make it as it was before means make it `i` again.

**Comment by Utkarsh1504** [comment]
> I will remake the pull request.

If you make another PR request these changes will be reflected again. Because your branch is `main`.
Ok, do one thing delete this repo from your account and fork it again.

**Comment by ParnaviKulkarni** [comment]
Yes I will do that.

**Pull request closed without merging**
