### PR TITLE
 Added upstream command

### LINKED ISSUE #61: suggested improvement Readme.md
### ⭐ Summary

The instructions require the local repository to set upstream as well for updated changes, which is currently missing the docs
Screenshot (2675)

### 💻 Location

readme.md

### ❌ Additional Info

_No response_

### PR DESCRIPTION
**Pull request by tanishagupta1**
Fixes #61

#### What Changes proposed in this pull request:

- Added command to set upstream in the local repository in Readme.md

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] Added documentation so that the program is self-explanatory and educational.
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/Utkarsh1504/DSA-Java/blob/main/CONTRIBUTING.md#requesting-a-lesson)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by tanishagupta1** [comment]
May you please add this pull request under hacktoberfest if find relevant. Thank You, Do let me know about any other required changes

**Comment by Utkarsh1504** [comment]
Thank you!

**Comment by Utkarsh1504** [comment]
@tanishagupta1 why you pushed these commits in this PR, please undo these changes which you have made later, and please make a new PR then push those commits.
I will suggest to you make a new branch otherwise you may face merging conflicts issues, I have given step by step instructions on how to use version control, please follow that.

**Comment by tanishagupta1** [comment]
Yes I completely got the point sorry for the inconvenience, I'll fix it

**Comment by tanishagupta1** [comment]
Can you pls guide me as to if I should fetch and merge with the upstream branch and again make the commit or as I reverted the commit, it doesn't seem to resolve the issue

**Comment by Utkarsh1504** [comment]
Ok, you just have reverted both the commits:
1. Add upstream command and
2. Add code in java
 
Now just make a commit for the adding upstream command again and That's it.

**Comment by tanishagupta1** [comment]
reverted to added upstream commit hope the issue is resolved now

**Comment by Utkarsh1504** [comment]
@tanishagupta1 yes you did it! Thank you!

**Comment by tanishagupta1** [comment]
Thank you for the help!

**Comment by Utkarsh1504** [comment]
Now In the future contribution please make a new branch and then contribute in that only, don't do contribution in the main branch.

**Comment by tanishagupta1** [comment]
yes definitely! taking the learnings with me.

**Pull request merged**
